version: '3.3'
services:
    postgis:
        image: postgis/postgis
        container_name: postgis
        environment:
            - POSTGRES_USER=toreglia
            - POSTGRES_PASSWORD=anthony
            - ALLOW_IP_RANGE=0.0.0.0/0
        ports:
            - '5432:5432'
        volumes:
            - 'pg_data:/var/lib/postgresql'
            - ./migration/bin/init/init.sh:/docker-entrypoint-initdb.d/init.sh
        restart: always
    flyway:
        image: flyway/flyway
        # postgres url schema: jdbc:postgresql://host:port/database
        command: -url=jdbc:postgresql://postgis:5432/breadcrumbs -user=toreglia -password=anthony -connectRetries=10 migrate info
        volumes:
            - ./migration/sql:/flyway/sql
        links:
            - postgis
        depends_on:
            - postgis
    app:
        build:
            context: ./app
        volumes:
            - .app/:/go/src/app
        ports:
            - "80:80"
        links:
            - postgis
        depends_on:
            - postgis
        environment:
            WAIT_HOSTS: postgis:5432

volumes:
    pg_data:
